services:
  nginx:
    container_name: nginx
    image: nginx:saba
    build: ./requirements/nginx/
    ports:
      - "443:443"
    depends_on:
      - wordpress
    restart : always
    volumes:
      - wp-data-volume:/var/www/html/
    networks:
      - inception
    env_file:
      - ./.env
    privileged: true

  vsftpd:
    container_name: vsftpd
    image: vsftpd:saba
    build: ./requirements/bonus/ftp
    volumes:
      - wp-data-volume:/var/www/html/
    ports:
      - "21:21"
    env_file:
      - ./.env
    restart: always
    networks:
      - inception
    depends_on:
      - wordpress
    privileged: true

  redis:
    container_name: redis
    image: redis:saba
    build: ./requirements/bonus/redis/
    volumes:
      - wp-data-volume:/var/www/html
    restart: always
    networks:
      - inception
    expose:
      - 6379
    depends_on:
      - wordpress

  mariadb:
    container_name: mariadb
    image: mariadb:saba
    build: ./requirements/mariadb/
    expose:
      - 3306
    volumes:
      - wp-db-volume:/var/lib/mysql
    restart : always
    env_file:
      - .env
    networks:
      - inception
    # privileged: true

  wordpress:
    container_name: wordpress
    image: wordpress:saba
    build: ./requirements/wordpress/
    expose:
      - 9000
    depends_on:
      - mariadb
    restart : always
    volumes:
      - wp-data-volume:/var/www/html/
    env_file:
      - ./.env
    networks:
      - inception
    privileged: true

  adminer:
    container_name: adminer
    image: adminer:saba
    build: ./requirements/bonus/adminer/
    ports:
      - "8080:8080"
    restart: always
    networks:
      - inception
    depends_on:
      - mariadb

  static-website:
    container_name: static-website
    image: static:saba-website
    build: ./requirements/bonus/static-website/
    ports:
      - "5484:5484"
    restart: always

  portainer:
    container_name: portainer
    image: portainer:saba
    build: ./requirements/bonus/portainer/
    ports :
      - "2307:2307"
    env_file:
      - ./.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

volumes:
  wp-db-volume:
    name: wp-db-volume
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: /home/aahlyel/data/db

  wp-data-volume:
    name: wp-data-volume
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: /home/aahlyel/data/data


networks:
  inception:
    name: inception
    driver: bridge
